# Project 2: Distributed Mini Google System 
# CS2510 - Distributed Operating Systems
# Amanda Crawford and Raphael Car

# Project Dependencies
# --- Python 3.6
# ---- psutils python library
# -----nltk python library 
# ----- nltk corpus needed : stopwords, punkt 
# The following commands can be used to run both a search system and index system:
# 
# 
# 

# 	### Search System Commands #####
# 	To run the search system, the master node must be running and listening or the worker nodes will not be able to start.To run the sea
# 
search_master:
	pip install psutils
	python3 search_master

search_worker:
	python 3 search_worker

search_worker_hydrogen:
	python 3 search_worker -m_host hydrogen.cs.pitt.edu

search_worker_hydrogen:
	python 3 search_worker -m_host hydrogen.cs.pitt.edu

search_tester:
	python search_tester.py keywords_search.txt localhost 9778 2